# Generated by Django 6.0.3 on 2026-04-05 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='placements.internshipplacement'),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logstatushistory',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='logs.weeklylog'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklylog',
            unique_together={('student', 'week_number', 'placement')},
        ),
    ]
