# Generated by Django 6.0.3 on 2026-04-26 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
        ('placements', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logstatushistory',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='weeklylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='weeklylog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='academic_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='academic_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='academic_grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='supervisor_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='supervisor_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='supervisor_signed_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logstatushistory',
            name='new_status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='logstatushistory',
            name='previous_status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='placements.internshipplacement'),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_WORK_APPROVAL', 'Pending Work Approval'), ('PENDING_ACADEMIC_EVALUATION', 'Pending Academic Evaluation'), ('COMPLETED', 'Completed'), ('RETURNED', 'Returned to Student')], default='DRAFT', max_length=40),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='week_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
