# Generated by Django 6.0.3 on 2026-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_logstatushistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='supervisor_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_WORK_APPROVAL', 'Pending Work Approval'), ('RETURNED', 'Returned to Student'), ('RESUBMITTED', 'Resubmitted by Student'), ('PENDING_ACADEMIC_EVALUATION', 'Pending Academic Evaluation'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=40),
        ),
    ]
