# Generated by Django 6.0.3 on 2026-04-05 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipplacement',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='workplace_supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'WORKPLACE_SUPERVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_placements', to=settings.AUTH_USER_MODEL),
        ),
    ]
